general {
    hide_cursor = false
}
background {
    monitor =
    path = /path/to/wallpaper.png
    blur_passes = 2
    blur_size = 4
    brightness = 0.6
    color = rgba(31, 31, 40, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(220, 215, 186, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(114, 113, 105, 1.0)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 42
    outline_thickness = 1
    outer_color = rgba(84, 84, 109, 1.0)
    inner_color = rgba(22, 22, 29, 1.0)
    font_color = rgba(220, 215, 186, 1.0)
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>enter password...</i>
    fail_color = rgba(228, 104, 119, 1.0)
    check_color = rgba(126, 156, 216, 1.0)
    rounding = 0
    fade_on_empty = false
    position = 0, -60
    halign = center
    valign = center
    dots_center = true
    dots_size = 0.25
    dots_spacing = 0.3
}

label {
    monitor =
    text = $USER@$HOST
    color = rgba(54, 54, 70, 1.0)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = 0, -30
    halign = center
    valign = bottom
}
label {
    monitor =
    text = kuma@arch
    color = rgba(54, 54, 70, 1.0)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = bottom
}

label {
    monitor =
    text = press enter to unlock
    color = rgba(84, 84, 109, 1.0)
    font_size = 11
    font_family = JetBrainsMono Nerd Font
    position = 0, -110
    halign = center
    valign = center
}

