
background = rgb(181616)
base = rgb(1d1c1c)
alternate_base = rgb(282727)

text = rgb(c5c9c5)
bright_text = rgb(dcd7ba)

accent = rgb(7e9cd8)
accent_secondary = rgb(957fb8)

font_family = JetBrainsMono Nerd Font
font_family_monospace = JetBrainsMono Nerd Font

font_size = 12
small_font_size = 10

rounding_large = 18
rounding_small = 10

icon_theme = Papirus-Dark

